### PR TITLE
Change the way to detect WSL to support WSL2

### PR DESCRIPTION
**Pull request by LumaKernel**

### CODE REVIEW

**Comment by LumaKernel** [comment]
Now, it will get this error.

```
Error detected while processing function openbrowser#_cmd_open[1]..<SNR>228__OpenBrowser_cmd_open[6]..<SNR>228__Open
Browser_open:
line   35:
E734: Wrong variable type for +=
```

**Comment by LumaKernel** [comment]
The last two commits are related to https://github.com/tyru/open-browser.vim/pull/142 .
If that was merged, please revert them ( or I do ) .

**Comment by LumaKernel** [comment]
Hi. Rebased.

**Comment by tyru** [comment]
@LumaKernel Hi.

I also want to check & merge this branch in the new Win 10 + WSL 2.
But the new Win 10 (May 2020 Update) has not been coming to my desktop yet.
So please wait patiently until the update is coming 🙏

**Comment by LumaKernel** [comment]
FYI: We can use `wslview` for this purpose.

**Comment by tyru** [comment]
Close this PR because of #154

**Pull request closed without merging**
